sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHdTAvLXSH6VUMx1195
    access-key-secret: QRdVkUvUb0hHu8rcWNdTY7eRAOtOD2
    bucket-name: sky-take-out-cbo
